version: '3'
services:
  web:
    container_name: nginx-alpine
    image: nginx:1.13.5-alpine
    ports:
      - "89:80"
    depends_on:
      - app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html

  app:
    container_name: php-alpine
    build: ./
    volumes:
      - ./php:/var/www/html
